name: GH-Pages/Master CI

on:
  push:
    branches: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate tag vars
        id: tagvars
        run: |
         echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
         echo "::set-output name=build_datetime::$(date -u +%Y%m%d-%H%M)"
         
      - name: Build and push Dockerimage to DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: litetex/t-rex-runner
          tags: "latest,master-${{ steps.tagvars.outputs.sha_short }}-${{ steps.tagvars.outputs.build_datetime }}"
